//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ЭлектронныйЖурналКурсовой.Данные
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ЭлектронныйЖурналСущность : DbContext
    {
        public ЭлектронныйЖурналСущность()
            : base("name=ЭлектронныйЖурналСущность")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<оценки> оценки { get; set; }
        public virtual DbSet<пользователи> пользователи { get; set; }
        public virtual DbSet<предмет> предмет { get; set; }
        public virtual DbSet<учебная_группа> учебная_группа { get; set; }
    }
}
