//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ЭлектронныйЖурналКурсовой.Данные
{
    using System;
    using System.Collections.Generic;
    
    public partial class пользователи
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public пользователи()
        {
            this.оценки = new HashSet<оценки>();
            this.предмет = new HashSet<предмет>();
            this.учебная_группа = new HashSet<учебная_группа>();
        }
    
        public int номер { get; set; }
        public string логин { get; set; }
        public string пароль { get; set; }
        public string имя { get; set; }
        public string фамилия { get; set; }
        public string отчество { get; set; }
        public string должность { get; set; }
        public System.DateTime дата_раждения { get; set; }
        public string группа { get; set; }
        public byte[] фото { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<оценки> оценки { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<предмет> предмет { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<учебная_группа> учебная_группа { get; set; }
    }
}
