//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ЭлектронныйЖурналКурсовой.Данные
{
    using System;
    using System.Collections.Generic;
    
    public partial class предмет
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public предмет()
        {
            this.оценки = new HashSet<оценки>();
        }
    
        public int номер_предмета { get; set; }
        public string предмет1 { get; set; }
        public int преподователь { get; set; }
        public string группа { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<оценки> оценки { get; set; }
        public virtual пользователи пользователи { get; set; }
        public virtual учебная_группа учебная_группа { get; set; }
    }
}
